<?php
namespace backend\models;

use yii\base\Model;

class LoginForm extends Model{
    //public $username;
    public $password;
    public $code;
    public $rememberMe;//璁颁綇鎴�

    public function rules()
    {
        return [
            [['username','password_hash'],'required'],
            ['code','captcha','captchaAction' => 'admin/captcha'],
            ['rememberMe','safe']//杩欎釜瀛楁鏄畨鍏ㄧ殑锛屼笉闇�瑕侀獙璇�
        ];
        //return parent::rules(); // TODO: Change the autogenerated stub
    }

    /*public function attributeLabels()
    {
        return parent::attributeLabels(); // TODO: Change the autogenerated stub
    }*/

}